service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: dist/apps/mono-svc/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-offline:
    httpPort: 3000  # Optional: specify the port you want to use
    noPrependStageInUrl: true  # Do not prepend the stage in the URL
